### ISSUE TITLE
Reload page after wallet transaction

### ISSUE THREAD

**Issue by codenamejason** [InsureNET/applications#3]
After making a transaction with your wallet the page does not refresh.

**Comment by codenamejason** [comment]
I am currently working on this I think I have the solution in place I need to do some more testing before I close this.

**Comment by drdavecode** [comment]
its a great concept to close the page, even build some intuitve stuff. Like AUTto scroll as the camera watchs your eyes LOL

**Comment by drdavecode** [comment]
The A.I i c give u in script and pieces if u can make something on it. Plus blinking tech for closures.

**Comment by drdavecode** [comment]
its just a bond between the refresh link and page displayed, all u have to do i think is add the page to refresh itself while transferring into there wallet, so a dual link. so u click wallet, goes to wallet, plus refres
hs page
